### ISSUE TITLE
Release zip contains folder inside folder

### ISSUE THREAD

**Issue by eSkiSo** [Confexion/Greenwing#1]
The release zip file (used by Kanboard to install the plugin) contains the folder Greenwing, this will create "plugins/Greenwing/Greenwing" path which will make the plugin not work.
Inside the zip file should only be the contents of the Greenwing folder not the folder it self.

**Comment by jbaubree** [comment]
Hi,
we are actually waiting for a fix from kanboard project directly.
Thank you for your understanding

**Comment by BlueTeck** [comment]
The problem does not belongs to Kanboard, but to the way you are creating your release ZIP file.

**Comment by jbaubree** [comment]
Unfortunatly, i'm creating my folder following kanboard'guide instructions. When i make it without folder in folder, my PR are rejected..

**Comment by BlueTeck** [comment]
Most other plugins create them using a makefile like this https://github.com/kanboard/plugin-gantt/blob/master/Makefile

**Comment by jbaubree** [comment]
I will try this thank you :)

**Comment by jbaubree** [comment]
Fixed
