### ISSUE TITLE
Gantt chart settings

### ISSUE THREAD

**Issue by ntimo** [Confexion/Greenwing#10]
Hello,
I just noticed that the settings for the [Gantt chart plugin
](https://github.com/kanboard/plugin-gantt) are displayed wrongly.

<img width="1447" alt="Screenshot 2019-10-31 at 17 30 08" src="https://user-images.githubusercontent.com/6145026/67986080-86afb980-fc2a-11e9-8995-0b922eb71153.png">

Best wishes,
Timo

**Comment by jbaubree** [comment]
Hi there,
we are actually working on a fix for that plugin and on a responsive version of Kanboard.
Thanks for waiting,

Greenwing Team

**Comment by jbaubree** [comment]
You can download Greenwing Version 1.2.0, we have fixed Gantt plugin and you can now have a responsive version of Kanboard.
Enjoy :)

**Comment by ntimo** [comment]
Thank you very much :)
