### ISSUE TITLE
Don't updating in kanboard

### ISSUE THREAD

**Issue by plyaskin** [Confexion/Greenwing#11]
Available just version 1.0.0, check the link to the github

**Comment by jbaubree** [comment]
Hello,

can you give me more details for your issue?
I actually don't understand your problem. When you are in kanboard's plugins list on the app,
just search Greenwing and click on install. You will have the actual version: 1.1.2.
Best reguards,

Greenwing Team

**Comment by plyaskin** [comment]
I have just installed the plugin.
![image](https://user-images.githubusercontent.com/9464550/68190908-ea4a3600-ffe0-11e9-970f-3839e787635d.png)
Link for the page of plugin is "https://github.com/.../..."

The "Update" button don't work
![image](https://user-images.githubusercontent.com/9464550/68191048-34cbb280-ffe1-11e9-9306-de7440d80667.png)

Check the links

**Comment by jbaubree** [comment]
Well,

we will take a look for a fix as soon as possible.
you can download last version of Greenwing using this link
https://github.com/Confexion/Greenwing/releases/download/v1.1.2/Greenwing.zip
thank you for this feedback,

Greenwing Team
