### ISSUE TITLE
text of the bar is hidden in Gantt charts

### ISSUE THREAD

**Issue by gguillemot** [Confexion/Greenwing#13]
The text in the bar of Gantt charts is hidden at the bottom. 

![image](https://user-images.githubusercontent.com/783994/68671694-343a9b00-0550-11ea-9f22-4b235abf0336.png)

**Comment by jbaubree** [comment]
Hello,

this is fixed by Greenwing version 1.2.1.
thank you for feedback

Greenwing Team
