### ISSUE TITLE
Drag and Drop functionality is not working

### ISSUE THREAD

**Issue by laingjan** [Confexion/Greenwing#15]
First of all great theme it really modernizes the look and feel of Kanboard. 
My issue is that upon installation in Kanboard ver 1.2.10 I cannot drag and drop cards across columns. Unfortunately I am  a novice at PHP so not sure where to look to correct it.
If I remove the plugin the drag and drop functionality returns to the default installation as well as other theme based plugins, only Greenwing doesn't allow for this.
Can you advise how to fix?

**Comment by jbaubree** [comment]
Hi,

Thanks for your feedback.
Normally, Greenwing's last version has no problem with drag and drop.
If you have actually this issue for your kanboard, give me more informations about this problem:
  - Your operating system
  - Your Web Browser
and what else you can give to help for a fix.

Greenwing Team

**Comment by vistar** [comment]
For me too.

Windows 7
Chromium 75
Greenwing 1.2.1
Kanboard: 1.2.12
PHP: 7.3.13-1
PHP SAPI: fpm-fcgi
Apache on Linux 3.16.0-10-amd64
MariaDB 10.0.38

No errors in browser's console.

**Comment by tamielbr** [comment]
Same here, and also expand/collapse tasks (pressing 's' on the keyboard) doesn't work.
Linux Mint 18
Firefox 74
Kanboard: 1.2.13
PHP version: 7.2.26

**Comment by jbaubree** [comment]
Hi,

After a few checks, there may actually be some conflicts with plugins.
We noted that BigBoard brings conflicts and we will work on it soon.
Thanks for your understanding,

Greenwing Team

**Comment by jbaubree** [comment]
Hi,

After working on a fix, we have notice that this issue does not appear for now.
If you get this bug again, please try to create issue on BigBoard project.
Thanks for your understanding,

Greenwing Team

**Comment by tamielbr** [comment]
Just to let you know, it doesn't work here - same problems. All others are fixed with 1.3.0 - big thanks! I will try to diagnose and see what aspects of the CSS are conflicting and let the BigBoard folks know.
