### ISSUE TITLE
Minor visual change

### ISSUE THREAD

**Issue by ivolvicente** [Confexion/Greenwing#16]
Hello, 
and first let me say that this is the best theme i have found for Kanboard.

I have a minor visual issue, my project dropdown dont have a white background like the readme screenshot (i like it more).

![image](https://user-images.githubusercontent.com/11926387/70721458-7ee53980-1ced-11ea-8e18-7920adcf90b7.png)

Finally i think that will be helpfull to have a simple background color change on hover in notification, new project and user dropdown options.

I can help, but the scss files are not provided.

Thanks

**Comment by jbaubree** [comment]
Hello ivolvicente,

thanks for your comment. Effectively, our README screenshots are not up to date.
About background colors on hover, we have make different graphic choices and this is our actual version that can change over time.
Be patient and thanks for your feedback.

Greenwing Team

**Comment by ivolvicente** [comment]
Hello @jbaubree 

Thanks for your reply, that's ok, i will add my css file to deal with this minor changes.
