### ISSUE TITLE
Request: Configure theme to works properly with Wiki Plugin

### ISSUE THREAD

**Issue by btd1337** [Confexion/Greenwing#18]
Would it be possible to improve the theme style when the [Wiki plugin](https://github.com/funktechno/kanboard-plugin-wiki) is installed?

![Captura de tela de 2020-01-16 12-10-29](https://user-images.githubusercontent.com/11943860/72536681-77b7cb00-3859-11ea-99d3-e0c638626b13.png)

![Captura de tela de 2020-01-16 12-11-07](https://user-images.githubusercontent.com/11943860/72536683-7c7c7f00-3859-11ea-8dd7-eec28b018f08.png)

**Comment by jbaubree** [comment]
Hi,

Thanks for your report, we are working on issue and will close this when it will be fixed.
Best regards,

Greenwing Team

**Comment by jbaubree** [comment]
Unfortunately, we can not fix all compatibility issues, we can not edit directly plugins and there is not always class or id to add style specifically.
We have fixed all we can in Greenwing 1.2.2 Version :)
