### ISSUE TITLE
Task Drag & drop functionality not working 

### ISSUE THREAD

**Issue by Darkdecenet** [Confexion/Greenwing#20]
If i have the theme installed along side customizer  the drag& drop functionalty doesn't work properly

**Comment by tamielbr** [comment]
Duplicate to #15

**Comment by tamielbr** [comment]
I had the same problem, but it was a conflict with the BigBoard plugin. Uninstalled, it works fine.

**Comment by jbaubree** [comment]
Duplicated, i close
