### ISSUE TITLE
Non minified version of CSS file

### ISSUE THREAD

**Issue by sh4nks** [Confexion/Greenwing#21]
Hi,

first of all, this is the best looking Kanboard theme available imho!

I do have a little request though, would it be possible to include the non minified CSS version of this theme as well (or if it exists, a SASS/LESS version)?

Thanks & all the best,
Peter

**Comment by jbaubree** [comment]
Hi,

We have decided to make available non-minified SCSS.
we are working on some documentation and will push this feature on nexts versions.

thanks
