### ISSUE TITLE
Local fonts do not show, giving 400 error

### ISSUE THREAD

**Issue by tamielbr** [Confexion/Greenwing#22]
Checked on Firefox console, all Monserrat fonts were giving 400 error.

might be a problem with '/plugins/Greenwing/src/fonts/...' in CSS. Inspector shows that it doesn't pick up base Kanboard installation directory (site.org/kanboard_install/) and instead picks up (site.org/) directly..

![Screenshot from 2020-04-01 19-40-37](https://user-images.githubusercontent.com/3904166/78193403-d2bc8f80-7450-11ea-8507-2df6e4c72e7c.png)

Want to make sure this is not only a local problem or a general fix needed.

**Comment by jbaubree** [comment]
Hi there,

we will work soon on a local installation of Montserrat fonts to be sure this issue will not occur again.
thanks for understanding,

Greenwing team

**Comment by jbaubree** [comment]
## Greenwing Version 1.2.1 uses font locally. Upgrade your Greenwing version and it will be fixed :)

**Comment by tamielbr** [comment]
Continues to be a problem here. Upgraded to 1.3.0 (it shows as 1.2.1 on Kanboard plugin page).
![Screenshot from 2020-07-06 16-12-04](https://user-images.githubusercontent.com/3904166/86630772-a52d3800-bfa3-11ea-902c-2a690380797a.png)

**Comment by jbaubree** [comment]
Oh, it seems to be Mozzilla bug..
Try to go to about:config on your browser,
Set security.fileuri.strict_origin_policy to false.
The origin policy is calculated based on the html, NOT the css file! So a font file right besides an css file might not work, which is very confusing. (At least this is what I thought was the case with Firefox!)

Kanboard plugin page just updated this morning, now it normally shows 1.3.0 version.

**Comment by djaybalaji** [comment]
Facing the same issue even with the latest version and on chrome.
![image](https://user-images.githubusercontent.com/33634637/89304096-aa58d200-d68a-11ea-869c-a994c213628e.png)

**Comment by tamielbr** [comment]
Tried now with the update, didn't work (Firefox/Mint).
