### ISSUE TITLE
Gantt Chart - Days do not match with month

### ISSUE THREAD

**Issue by sh4nks** [Confexion/Greenwing#23]
Hi,

I have found another little bug - the days do not match the months as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/1510708/78767227-9aeea400-798a-11ea-8e2b-108f5eb1f5dc.png)

If you tell me where I have to look for this to fix it I could give it a try!

**Comment by jbaubree** [comment]
Hi,
thanks for your your report, we will work soon on a fix :)

Greenwing team

**Comment by jbaubree** [comment]
Fixed in Greenwing 1.2.2 Version :)
