### ISSUE TITLE
Small fix in Wiki plugin

### ISSUE THREAD

**Issue by btd1337** [Confexion/Greenwing#24]
First, congratulations on this great job.

Second, Could u just add a margin-left in the  Wiki title section?

![Captura de tela de 2020-04-10 16-03-37](https://user-images.githubusercontent.com/11943860/79016265-e2b92b00-7b44-11ea-8c10-498dc191eca9.png)

**Comment by btd1337** [comment]
The table too isn't good in low resolutions.

![IMG_20200410_221147](https://user-images.githubusercontent.com/11943860/79037707-e59a3700-7ba9-11ea-8637-2cf92f44c3ee.jpg)

**Comment by jbaubree** [comment]
Hi,
thank you for your feedback, unfortunately, i can't add this margin left :/
for law resolution adaptation, this will be fixed in next version.
Thanks

**Comment by jbaubree** [comment]
This is fixed in Greenwing v1.3.0
Enjoy :)
