### ISSUE TITLE
Overdue tasks don't show in different color

### ISSUE THREAD

**Issue by tamielbr** [Confexion/Greenwing#25]
Couldn't find `.task-date-overdue` class in CSS so it seems like overdue tasks don't show up in different color. I tried setting this in the Settings to override the CSS, but nothing seems to override the theme. Is this the case?

**Comment by jbaubree** [comment]
Hi,

can you give me more details about where ".task-date-overdue" does appear?

**Comment by tamielbr** [comment]
Sorry, should've been more specific! From the [Kanboard manual](https://docs.kanboard.org/en/latest/user_guide/tasks.html):

> Due Date: Overdue tasks will have a red due date and upcoming due dates will be black on the board.

In looking at the code in the repository here, i couldn't find a mention to the class `.task-date-overdue`, which I assume is what makes this change of color happen. I am not absolutely sure it is, but in any case, overdue tasks show in the same color as all the others.

**Comment by jbaubree** [comment]
Hi,

i understand your problem and will fix it for next version.
thanks for your feedback,

Greenwing Team

**Comment by jbaubree** [comment]
This is fixed in Greenwing v1.3.0
Enjoy :)
