### ISSUE TITLE
Design issues with Due Date plugin

### ISSUE THREAD

**Issue by tamielbr** [Confexion/Greenwing#26]
There seems to be a general issue with the spacing and buttons with [Due Date plugin](https://github.com/dmorlitz/kanboard-duedate).

![due_date](https://user-images.githubusercontent.com/3904166/79703932-274f6f80-8285-11ea-895c-0a70d09c4214.png)

It also seems to be blocking functionality but I am still investigating, similar to [this issue](https://github.com/dmorlitz/kanboard-duedate/issues/6).

**Comment by jbaubree** [comment]
Hi, we will try to fix this as soon as possible.
Thanks

Greenwing Team

**Comment by jbaubree** [comment]
Hi, this issue will be fixed in next Greenwing version :)
Thanks

Greenwing Team

**Comment by jbaubree** [comment]
This is fixed in Greenwing v1.3.0
Enjoy :)
