### ISSUE TITLE
Error updating plugin on Kanboard

### ISSUE THREAD

**Issue by btd1337** [Confexion/Greenwing#27]
When trying to update the Plugin to version `1.2.2` the error message is displayed:

```
The plugin file could not be opened.
```

Note that the `Plugin.php` file is returning `1.2.1` version.

**Comment by tamielbr** [comment]
I get no error message (didn't enable) but I get thrown back to the plugins page, nothing happens, no update.

**Comment by jbaubree** [comment]
Hi,
this issue seems to be from Kanboard official website. We are working on it to fix this issue soon.
Thanks for understanding

Greenwing Team
