### ISSUE TITLE
Design issues with CardPushDate

### ISSUE THREAD

**Issue by tamielbr** [Confexion/Greenwing#28]
Just noticed this as well, conflict with https://github.com/dmorlitz/kanboard-CardPushDate. Seems to put two avatars at once. Perhaps the other design issues will be solved together, but this might help diagnose.

![Screenshot from 2020-06-19 12-32-07](https://user-images.githubusercontent.com/3904166/85150964-974c8880-b229-11ea-9aac-c6071498860d.png)

**Comment by jbaubree** [comment]
Hi,

This issue will be fixed in next greenwing version.
Thanks for your feedback,

Greenwing Team

**Comment by jbaubree** [comment]
This is fixed in Greenwing v1.3.0
Enjoy :)
