### ISSUE TITLE
drag & drop tasks

### ISSUE THREAD

**Issue by ivanionut** [Confexion/Greenwing#3]
Hi,
I wanted to know the tasks can't be dragged, or is it my problem?

_P.S. beautiful theme!_

**Comment by jbaubree** [comment]
Hello,
There is no report of this type nowdays.
Try to disable others plugins, this mat resolve your issue. 
Thanks for your report,
Greenwing team

**Comment by ivanionut** [comment]
hi, I confirm you ... the problem was a plugin ...
