### ISSUE TITLE
Compatibility with BigBoard

### ISSUE THREAD

**Issue by johnwoltman** [Confexion/Greenwing#31]
Would it be possible to get support for BigBoard? There's been some active development with it recently, and I'm using it in my own Kanboard installation.

If there's some work that needs to happen on the BigBoard to help make it compatible, perhaps I can help with that.

**Comment by jbaubree** [comment]
Hello,

We want to give the best experience with compatibility with other plugins. Can you give us more details about what exactly does not work well with BigBord plugin?
We will do our best to fix that as soon as possible.

Thanks,

Greenwing Team

**Comment by johnwoltman** [comment]
Sure (and thanks for the quick response).  Here are two screenshots that show the issues.  It's mostly spacing and some borders issues.

![bigboard_with_greenwing](https://user-images.githubusercontent.com/2498295/92984625-7fc41b00-f479-11ea-8f15-f7eea9be7a4e.png)
![bigboard_with_default](https://user-images.githubusercontent.com/2498295/92984626-7fc41b00-f479-11ea-9fd6-505a6eb22391.png)

**Comment by jbaubree** [comment]
Thank you for your help, we will work on it soon :)

**Comment by johnwoltman** [comment]
Let me know if

**Comment by johnwoltman** [comment]
(Sorry I accidentally clicked the close with comment button)

**Comment by jbaubree** [comment]
Hello,

You can now download Greenwing version 1.3.1 that takes in charge most of BigBoard plugin fix.
We are sorry that some issues like icons can not be override because BigBoard plugin do not follow some html semantics and has no specific class/id linked.
We hope you will enjoy spacing issues fixed :)

Greenwing Team

**Comment by johnwoltman** [comment]
Thank you! Like you said, it fixed the spacing issues, and it looks really good.  I think I'll take a look at the BigBoard code to see if I can get the icons to style properly.  Thanks again for fixing this :)
