### ISSUE TITLE
Changing Color

### ISSUE THREAD

**Issue by phatair** [Confexion/Greenwing#32]
Hello,
thanks for this great theme but i have one problem.
I see that there is a colormodel.php where i can change the color of the theme.
But i dont understand how to do this? There is no GUI for changing the color.
Is it necessary to change this in the colormodel.php and if yes, how can i do this.

We want to change the color of the header from dark blue to light blue.

Thank you very much.

**Comment by jbaubree** [comment]
Hello,

ColorModel.php is used for task colors not theme color.
If you want to change theme colors or header color, you have to follow customize guide here:
https://github.com/Confexion/Greenwing#customize-guide
You will be able next to edit sass/modules/_colors.scss or directly sass/layout/_header.scss.
