### ISSUE TITLE
Moving tasks results in the "working" indicator never disappearing

### ISSUE THREAD

**Issue by johnwoltman** [Confexion/Greenwing#33]
Something I found on the latest version is that when I move tasks to a new column, the task becomes 'grayed' out and the little animated "working" circle doesn't disappear until I refresh the page.  The issue does not occur with Kanboard's default skin.

I'm using:

- Kanboard 1.2.15
- Bigboard
- Greenwing (from the ZIP file and also tried with just cloning the repo)
- Firefox 80.0.1

**Comment by LibelleY** [comment]
I had the same issue. It's caused by the incopatible plugin "BigBoard": https://github.com/kanboard/kanboard/issues/4545#issue-639865019. Deinstalling BigBoard solved the problem for me.
