### ISSUE TITLE
No tags display on board

### ISSUE THREAD

**Issue by Gatomlo** [Confexion/Greenwing#39]
Hy,

I can see my tag in the list view but not in the board view. Is it normal ? Is there a way to change that ?
![Screenshot_5](https://user-images.githubusercontent.com/13197179/109165392-cb465900-777b-11eb-8993-0b5912bed947.png)
![Screenshot_6](https://user-images.githubusercontent.com/13197179/109165395-cb465900-777b-11eb-8042-ad87e4ac0fcc.png)

**Comment by AlexDiamante** [comment]
With this theme i see duplicated tags, if i remove the theme i just ree the default not duplicated tags
![duplicate tags](https://user-images.githubusercontent.com/80273182/110345421-d7a99c00-802e-11eb-8066-ad8450f0ce9d.jpg)

**Comment by AlexDiamante** [comment]
> With this theme i see duplicated tags, if i remove the theme i just ree the default not duplicated tags
> ![duplicate tags](https://user-images.githubusercontent.com/80273182/110345421-d7a99c00-802e-11eb-8066-ad8450f0ce9d.jpg)

Removed all the other plugins and it's perfect!

**Comment by AlexDiamante** [comment]
The conflict was with the other plugin "TaskProgressBar"
