### ISSUE TITLE
Compatibility issue with Gantt plugin

### ISSUE THREAD

**Issue by danielroehrig** [Confexion/Greenwing#4]
With the greenwing theme activated, it's currently impossible to use the gantt plugin.
![grafik](https://user-images.githubusercontent.com/12596513/65177667-72877280-da57-11e9-846e-ce7ac2633d6e.png)
It seems the gantt diagram is behind the header.

**Comment by jbaubree** [comment]
Hello,
you can now download the Greenwing 1.0.1 release.
This Greenwing version is now compatible with Gantt plugin.
Best reguards,
Greenwing Team

**Comment by danielroehrig** [comment]
Seems to be working just fine. Thanks!
