### ISSUE TITLE
Kanboard 1.2.20: access denied

### ISSUE THREAD

**Issue by MatzeMuc86** [Confexion/Greenwing#47]
When updating kanboard to v 1.2.20 I get a browser prompt "permission denied" when moving tasks on the board. I tried to identify what is causing this and realized uninstalling greenwing stops the issue.

**Comment by wucherpfennig** [comment]
Please see more details about this issue here: https://github.com/kanboard/kanboard/issues/4834

**Comment by billy-syrett** [comment]
I'm not a PHP developer so I'm not 100% sure but I reckon the issue might be coming from this commit adding a CSRF check:
[Add missing CSRF checks](https://github.com/kanboard/kanboard/commit/71123b0f378425229db6911984a90f5ee9953420)

**Comment by dtodor** [comment]
This still seems to be an issue, "access denied" is shown even with the latest commits.
