### ISSUE TITLE
Card Drag&Drop problems

### ISSUE THREAD

**Issue by deembi4** [Confexion/Greenwing#51]
After installing an error message appeared "Access is denied", while card drag&drop action. If uninstalled - it's ok.
Btw AMAZING theme, thanks.

**Comment by raenur** [comment]
Confirming the same issue using kanboard 1.2.20 - when I try to move a card between columns I get an "Access forbidden" message. Removing Greenwing the default theme allows cards to be moved.

**Comment by thatguy-za** [comment]
Just installed Kanboard and Greenwing and I also experience this issue.

**Comment by TobiasNils** [comment]
> Confirming the same issue using kanboard 1.2.20 - when I try to move a card between columns I get an "Access forbidden" message. Removing Greenwing the default theme allows cards to be moved.

Same here. 

**Setup**: 
* nginx version: nginx/1.18.0 (Ubuntu)
* database: postgresql 13
* Ubuntu Server 20.04.2 LTS (GNU/Linux 5.4.0-1038-raspi aarch64)
* Greenwing [release 1.3.1](https://github.com/Confexion/Greenwing/releases/tag/1.3.1)

**Comment by TobiasNils** [comment]
>     * Greenwing [release 1.3.1](https://github.com/Confexion/Greenwing/releases/tag/1.3.1)

I just tried out the cloning the mater branch into the `kanboard/plugins` folder, (followed by `sudo chown -R www-data:www-data /path/to/kanboard/plugins`, of course) and drag and drop works.

**Comment by bunomonteiro** [comment]
Thks, @TobiasNils!
There is an approved PR ([49](https://github.com/Confexion/Greenwing/pull/49)) that fixed this issue.

**Comment by thatguy-za** [comment]
@bunomonteiro has this fix been released? If so, which version was it released with?

**Comment by bunomonteiro** [comment]
@thatguy-za unfortunately, there is no version with this fix, as I could see :pensive:

(ps: I'm not a [Greenwing](https://github.com/Confexion/Greenwing/graphs/contributors) collaborator nor a contributor [yet])

**Comment by jbaubree** [comment]
Sorry for this response time...
I have just released this fixes on Greenwing Version 1.3.2.
I hope you enjoy this theme :)

**Comment by thatguy-za** [comment]
Woohoo! I've just updated and it works perfectly. Thanks @jbaubree

**Comment by sky4055** [comment]
> 
> 
> Woohoo! I've just updated and it works perfectly. Thanks @jbaubree

same here, Thanks !

**Comment by bunomonteiro** [comment]
s/o to  @alirezarayej for a nicely written PR proposal! clap clap clap

**Comment by katywings** [comment]
Thank you @jbaubree :tada:
