### ISSUE TITLE
Options from third party plugins are broken

### ISSUE THREAD

**Issue by ntimo** [Confexion/Greenwing#7]
Hello,
I have a few third party plugins installed like task2pdf or markdownplus when I go to `/settings/application` the options look a bit broken. 

<img width="1677" alt="Screenshot 2019-10-23 at 15 38 16" src="https://user-images.githubusercontent.com/6145026/67398637-42c61000-f5ab-11e9-8063-5505c0eeaebc.png">

Best wishes,
Timo

**Comment by jbaubree** [comment]
Hi ntimo,

we will work on your feedbacks as soon as possible.
thanks for your understanding,

Greenwing Team

**Comment by jbaubree** [comment]
Hello ntimo,

You can now download the Greenwing v1.1.0.
We have just fixed login page translator, compatibility with task2pdf plugin and you can now add a custom logo with Greenwing theme.
You can now close your issues and enjoy Greenwing.
Thank you for your comments,

Greenwing Team

**Comment by ntimo** [comment]
It seems like the fix only fixed the options from the task2pdf plugin but not the other two plugins ([markdownplus](https://github.com/creecros/MarkdownPlus) and [groupassign](https://github.com/creecros/Group_assign)).
<img width="1430" alt="Screenshot 2019-10-24 at 16 34 46" src="https://user-images.githubusercontent.com/6145026/67496178-50979600-f67c-11e9-9b87-e133b68fcf61.png">

**Comment by ntimo** [comment]
Thank you for fixing this so fast, your rock.
