### ISSUE TITLE
Mobile friendlyness

### ISSUE THREAD

**Issue by ntimo** [Confexion/Greenwing#8]
Hello together,
I know this is not really a  Greenwing issue since kanboard has never been really mobile friendly, but maybe the theme could improve the mobile friendliness just a little bit. Currently it looks like this :( 

<img width="402" alt="Screenshot 2019-10-27 at 09 49 48" src="https://user-images.githubusercontent.com/6145026/67632127-b2841580-f89f-11e9-8163-d9b720f9227d.png">

Best wishes,
Timo

**Comment by jbaubree** [comment]
Hi,
we will work on a kanboard responsive version with Greenwing soon.
there is a little work for that and we will do our best to push this feature quickly.
thanks,

Greenwing Team
