### ISSUE TITLE
Support for kanboard-plugin-wiki plugin

### ISSUE THREAD

**Issue by danieleteti** [Confexion/Greenwing#9]
While this theme is quite nice, we cannot use it bacause is not compatibile with the [Calendar](https://github.com/kanboard/plugin-calendar) plugin and the [Wiki](https://github.com/funktechno/kanboard-plugin-wiki) plugin.

It is possibile to make it compatibile?

Thank you for your work

**Comment by jbaubree** [comment]
Hello,

you can now download Greenwing v1.1.2 who is compatible with Calendar and Wiki plugin.
For Wiki plugin, if you want a better compatibility, ask them to add a specific body class to spot the plugin and do better style. 
Thanks for feedback,

Greenwing Team
